accessLogsFile = "/dev/stdout"
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
 
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]
            [[entryPoints.https.tls.certificates]]
             certFile = "/cert/certificate.crt"
             keyFile = "/cert/key.key"

[api]

[ping]

[docker]

watch = true

swarmmode = true

[[tls]]
  entryPoints = ["https"]
  [tls.certificate]
    certFile = "/cert/certificate.crt"
    keyFile = "/cert/key.key"